### PR TITLE
Edit Style and Display of Ui to match prototype

### PR DESCRIPTION
**Pull request by jamz903**

### CODE REVIEW

**Review by woojiahao — APPROVED** [review]
LGTM, just minor comment about the color of the "results" section where it looks a bit too similar to the BG, but other than that, looks good!

**Comment by jamz903** [comment]
Proposing to merge regardless of failing codecov, PR is failing from the removal of AddressBook dependencies in the previous commit. (View PR #75)

**Review by woojiahao — APPROVED** [review]
Awesome, LGTM, good work!

Screenshot 2023-10-18 at 09 52 27

**Comment by woojiahao** [comment]
@jamz903 Might want to re-run some of the CI for Java

**Review by lipwei1808 — APPROVED** [review]
LGTM

**Pull request merged**
